Guia do Usuário
------------

Esta parte da documentação, que é na maior parte em prosa, inicia com algumas
informações básicas sobre Flask, em seguida, concentra-se em passo-a-passo
e instruções para desenvolvimento web com Flask.

.. toctree::
   :maxdepth: 2

   foreword
   advanced_foreword
   installation
   quickstart
   tutorial/index
   templating
   testing
   errorhandling
   config
   signals
   views
   appcontext
   reqcontext
   blueprints
   extensions
   shell
   patterns/index
   deploying/index
   becomingbig

Referência da API
-------------

Se você está procurando informações sobre uma função específica, classe ou
método, esta parte da documentação é para você.

.. toctree::
   :maxdepth: 2

   api

Notas adicionais
----------------

Notas de Design, informações jurídicas e changelog aqui para os interessados​​.

.. toctree::
   :maxdepth: 2

   design
   htmlfaq
   security
   unicode
   extensiondev
   styleguide
   upgrading
   changelog
   license
